### ISSUE TITLE
[bug] Panic when deploying a new version of a currently running job

### ISSUE THREAD

**Issue by ewrenn8** [k14s/kapp#113]
## Repo Steps:

1. `kapp deploy -a app -f job.yml` where job.yml contains:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  annotations:
    kapp.k14s.io/versioned: ""
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["sleep 6000"]
      restartPolicy: Never
```
1. In a new terminal window, update the job yaml:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  annotations:
    kapp.k14s.io/versioned: ""
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: [""]
      restartPolicy: Never
```
1. In terminal window 2, rerun `kapp deploy -a app -f job.yml`

## Output
```
Changes

Namespace  Name      Kind  Conds.  Age  Op      Wait to    Rs       Ri
default    pi-ver-1  Job   -       14s  -       reconcile  ongoing  Waiting to complete (1 active, 2
                                                                    failed, 0 succeeded)
^          pi-ver-2  Job   -       -    create  reconcile  -        -

Op:      1 create, 0 delete, 0 update, 1 noop
Wait to: 2 reconcile, 0 delete, 0 noop

Continue? [yN]: y

2:29:30PM: ---- applying 2 changes [0/2 done] ----
2:29:30PM: noop job/pi-ver-1 (batch/v1) namespace: default
2:29:30PM: create job/pi-ver-2 (batch/v1) namespace: default
2:29:31PM: ---- waiting on 2 changes [0/2 done] ----
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x1bd392d]

goroutine 750 [running]:
github.com/k14s/kapp/pkg/kapp/resources.IdentifiedResources.Get(0x21a78e0, 0xc000426c30, 0xc0005060a0, 0x1, 0x1, 0x214a980, 0xc00048d440, 0xc000380700, 0x2178240, 0xc00048ff80, ...)
	github.com/k14s/kapp@/pkg/kapp/resources/identified_resources.go:86 +0x4d
github.com/k14s/kapp/pkg/kapp/clusterapply.AddOrUpdateChange.IsDoneApplying(0x2185d40, 0xc00003aa80, 0x21a78e0, 0xc000426c30, 0xc0005060a0, 0x1, 0x1, 0x214a980, 0xc00048d440, 0xc000380700, ...)
	github.com/k14s/kapp@/pkg/kapp/clusterapply/add_or_update_change.go:254 +0x160
github.com/k14s/kapp/pkg/kapp/clusterapply.(*ClusterChange).isDoneApplying(0xc000363600, 0xc0006ca730, 0x3, 0x3, 0xc0006ca72a, 0x1013c50, 0xc000046310, 0x0, 0x0)
	github.com/k14s/kapp@/pkg/kapp/clusterapply/cluster_change.go:173 +0x3ae
github.com/k14s/kapp/pkg/kapp/clusterapply.(*ClusterChange).IsDoneApplying(0xc000363600, 0x0, 0xc000040310, 0xc0000b0788, 0xc0006ca701, 0x3, 0x2, 0x1b67500, 0x2000102021928)
	github.com/k14s/kapp@/pkg/kapp/clusterapply/cluster_change.go:160 +0x43
github.com/k14s/kapp/pkg/kapp/clusterapply.(*WaitingChanges).WaitForAny.func1(0xc000046300, 0xc000394af0, 0xc000363600, 0xc0000fdaa0)
	github.com/k14s/kapp@/pkg/kapp/clusterapply/waiting_changes.go:66 +0x91
created by github.com/k14s/kapp/pkg/kapp/clusterapply.(*WaitingChanges).WaitForAny
	github.com/k14s/kapp@/pkg/kapp/clusterapply/waiting_changes.go:62 +0xc4
```

## Expected
Should error gracefully, if this isn't supported behavior, or should successfully install a new job (not sure what should happen to the previous job).
