### ISSUE TITLE
provide a way to specify min/max required version for k8s cluster

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp#120]
it seems that some configuration providers (eg https://github.com/cloudfoundry/cf-for-k8s/blob/master/supported_k8s_versions.yml) will benefit from ability to specify min/max version of supported k8s. we should also provide a way to bypass this check for users that do not care about it.

```yaml
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 1.26.0 # kapp binary version

minimumRequiredKubernetesVersion: 1.18.0 # <--
maximumRequiredKubernetesVersion: 1.19.0 # <--
```

- figure out how this works with some k8s cluster versions that have all kinds of suffixes (what does kubectl version code do)
