### ISSUE TITLE
Resources edited by controllers get overwritten by Kapp on each deploy

### ISSUE THREAD

**Issue by lucaschimweg** [k14s/kapp#124]
Concrete Problem: 
We install cf4k8s using `Kapp-controller`. During that process, a `ServiceAccount` is created, already containing a secret. Kubernetes' Service Account Admission Controller creates the service-account secret for this service account and adds it to the object (now containing 2 secrets). During the next check, Kapp-controller sees a difference between the specified object (without the created secret = containing 1 secret) and the actual object in the cluster (which contains the two secrets), therefor it updates the `ServiceAccount` object and deletes the reference to the just created secret.

This process gets repeated all the time and several thousand secrets get created, polluting the cluster. 

Is there any way to tell kapp not to remove the created reference? Other Objects with get augmented by controllers in the cluster will most probably have similar problems. This problem does not occur without a predefined secret inside the service account.

Minimal configuration for reproduction:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account
secrets: 
  - name: test
```

After the second secret was added to the service account, kapp wants to update the object on redeploy (which should not happen).

**Comment by lucaschimweg** [comment]
To achieve the desired handling, the following config can be used:

```yaml
apiVersion: kapp.k14s.io/v1alpha1
kind: Config

diffAgainstLastAppliedFieldExclusionRules:
- path: [secrets]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: ServiceAccount}
```

maybe this should be the default handling?
