### ISSUE TITLE
support array item with string as an affected resource ref by versioned resource

### ISSUE THREAD

**Issue by jamespollard8** [k14s/kapp#128]
We have a role that looks like this:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kpack-webhook-certs-admin
  namespace: kpack
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - webhook-certs
```

and we'd like the `webhook-certs` secret to be properly versioned.

We looked into PR-ing this change ourselves to `pkg/kapp/config/default.go` but are unsure how to do the correct, general level of matching for a relatively special case like this.

Within this section
```
templateRules:
...
- resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: Secret}
```
we started writing this:
```
    - path: [rules, {allIndexes: true}, {allIndexes: true}, resourceNames, {allIndexes: true}]
      resourceMatchers: [apiVersionKindMatcher: {apiVersion: v1, kind: Role}]
```

But we're worried that secrets and not-secrets might live together within the `resourceNames` section, for example.

**Comment by jamespollard8** [comment]
cc my pair @syslxg

**Comment by cppforlife** [comment]
to me this doesnt feel like something that belongs in defaults. but i could see it as a project specific configuration.

```
- path: [rules, {index: 1}, resourceNames, {allIndexes: true}]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: Role}
```

i dont recall if we allow array item at the end of the path at this point, but we could add support for that.

**Comment by jamespollard8** [comment]
Ah cool - that `{index: <number>}` tip is helpful. Is there a way to match that on a specific key?

Is this (https://github.com/k14s/kapp/blob/develop/docs/config.md) the right doc for figuring out how to apply project-level configuration for template rules?

**Comment by cppforlife** [comment]
> Is there a way to match that on a specific key?

do you mean by key-value within an array item instead of an index?

> Is this (https://github.com/k14s/kapp/blob/develop/docs/config.md) the right doc for figuring out how to apply project-level configuration for template rules?

yup.

**Comment by jamespollard8** [comment]
>do you mean by key-value within an array item instead of an index?

Yeah, that's what I mean.

**Comment by aaronshurley** [comment]
@jamespollard8 anything else we can help y'all with?

**Comment by jamespollard8** [comment]
The last ask/question here is whether there's a way to match on a specific item within a map instead of by hard-coded index. Other than that, I think it's fair to close this with this resolution:

Our specific ask/use case here is too specific to put into kapp defaults. The recommendation from the kapp team is to configure this logic at the project level, which seems straightforward enough - but I do think it's a new mechanism for cf-for-k8s.

**Comment by cppforlife** [comment]
> The last ask/question here is whether there's a way to match on a specific item within a map instead

this one is interesting in this case. what would you match by, may be this?

```
apiGroups:
- ""
resources:
- secrets
```

but what if that item was modified to

```
apiGroups:
- ""
resources:
- secrets
- configmaps
```

**Comment by jamespollard8** [comment]
Yeah. We'll get something working for now and may need to revisit if we run into the more tricky case.

**Comment by Neonox31** [comment]
> to me this doesnt feel like something that belongs in defaults. but i could see it as a project specific configuration.
> 
> ```
> - path: [rules, {index: 1}, resourceNames, {allIndexes: true}]
>   resourceMatchers:
>   - apiVersionKindMatcher: {apiVersion: v1, kind: Role}
> ```
> 
> i dont recall if we allow array item at the end of the path at this point, but we could add support for that.

@cppforlife I tried your recommendation but the versioned secret is not injected, here is my kapp config : 
```yaml
apiVersion: kapp.k14s.io/v1alpha1
kind: Config

templateRules:
  - resourceMatchers:
      - apiVersionKindMatcher: { apiVersion: v1, kind: Secret }
    affectedResources:
      objectReferences:
        - path: [rules, { index: 1 }, resourceNames, { allIndexes: true }]
          resourceMatchers:
            - apiVersionKindMatcher: { apiVersion: rbac.authorization.k8s.io/v1, kind: Role }
```
and resources :
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: ovh-credentials
  namespace: cert-manager
  annotations:
    kapp.k14s.io/versioned: ""
data:
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-ovh:secret-reader
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - ovh-credentials
  verbs:
  - get
  - watch
```
Is this normal in your opinion ?
