### ISSUE TITLE
support configuring Service in one app to point to another (currently label scoping injects its own app label)

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp#13]
Darrell Turner via Slack (https://kubernetes.slack.com/archives/CH8KCCKA5/p1559311705003900):

> I'm running across an issue w/ kapp that seems to be by design but conflicts with what i want to do.  I want to deploy my app as 2 seperate kapps one that does the deployment/release/pods and the other that does the services.  I'm doing this so I can have blue/green type deployments w/ multiple apps, and just one set of services.  Everything works awesome EXCEPT kapp is adding to my service selector something to limit itself to the same app.  Since my app is installed as a seperate kapp name my selector can never match.  If i manually remove the selector it all works great.

Currently default label scoping rules inject its own app label into Service's spec.selector [1]. Let's for now add an annotation to opt out of label scoping per resource.

[1] https://github.com/k14s/kapp/blob/bcd3c139498a90cfbaa805cbe7cb19349671a1df/pkg/kapp/config/default.go#L150-L153

**Comment by cppforlife** [comment]
it may also be worth adding functionality to replace "symbolic" app label with actual label so that scoping works across multiple apps. e.g.

```yaml
kind: Service
...
spec:
  selector:
    dep: backend
    kapp.k14s.io/app: another-app # <-- will be replaced with a label of app called "another-app" TODO namespaces...
```
