### ISSUE TITLE
kapp: rebaseRule for Aggregated ClusterRoles

### ISSUE THREAD

**Issue by yanniszark** [k14s/kapp#140]
Kubernetes has something called [aggregated ClusterRoles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles).
Basically, when an `aggregationRule` is specified on a ClusterRole, Kubernetes will automatically fill the `rules` field with the aggregated rules of the ClusterRoles that match the given selector.

I saw that `kapp` already has already foreseen the use-case of certain fields out of the user's control.
That's why the `rebaseRules` exist.

However, I'm not sure I can write a `rebaseRule` with the current syntax.
What I want to define is:
`The rules field is controlled by another entity IF the `aggregationRule` field is not empty.`

Does it make sense to provision for this kind of use-case with something like a `notEmptyFieldMatcher`?

**Comment by cppforlife** [comment]
> The rules field is controlled by another entity IF the aggregationRule field is not empty.
> Does it make sense to provision for this kind of use-case with something like a notEmptyFieldMatcher?

yeah, that makes sense.

currently ive seen folks apply rebase rule against a specific ClusterRole matching it by name/namespace, but of course that's not as generic as one may want.

**Comment by cppforlife** [comment]
implemented matched in https://github.com/k14s/kapp/commit/56c33f30d9ce3dd9e0a032f51679343284c30de6 (will be included in the next release). i havent added it as a default rebase rule though.

was using following yaml to test:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.example.com/aggregate-to-monitoring: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-endpoints
  labels:
    rbac.example.com/aggregate-to-monitoring: "true"
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:
- path: [rules]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - notMatcher:
      matcher:
        emptyFieldMatcher:
          path: [aggregationRule]
```
