### ISSUE TITLE
Overwriting resource ownership doesn't propagate to PVCs of StatefulSets

### ISSUE THREAD

**Issue by ig0rsky** [k14s/kapp#151]
Just deployed an app with another label (overwriting existing set of resources in the cluster with the new app label), the PVCs that are spawned from the StatefulSet VolumeClaims are still lingering on the old app label. Is this desired behaviour? 

Had to manually patch the labels on the PVCs.

**Comment by cppforlife** [comment]
@ig0rsky im assuming you are referring to use of `--dangerous-override-ownership-of-existing-resources`?

i am not too surprised that volume claims arent being relabeled because statefulset controller has quite a bit of non-converging behaviour (e.g. https://github.com/kubernetes/kubernetes/issues/74916). kapp does not "own" resources that were created by other resources (it just tracks them) like statefulset hence it's not going to directly modify them but rather expects "true owner" to converge them based on its configuration.

feel free to include example config and steps you've done so i can double check if this is expected.

**Comment by ig0rsky** [comment]
> @ig0rsky im assuming you are referring to use of --dangerous-override-ownership-of-existing-resources?  

Yes.

> i am not too surprised that volume claims arent being relabeled because statefulset controller has quite a bit of non-converging behaviour (e.g. kubernetes/kubernetes#74916). kapp does not "own" resources that were created by other resources (it just tracks them) like statefulset hence it's not going to directly modify them but rather expects "true owner" to converge them based on its configuration.

I've also seen this thread while looking for a solution to a prior issue with StatefulSets (deletes were not propagated, but I found out that there's an annotation for deletion ownership which you've added I presume as a workaround for this case specifically.)

Here's an example: 
```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bugdemo-statefulset
  labels:
    app: bugdemo-statefulset
    extraLabel: fromStatefulSet
spec:
  selector:
    matchLabels:
      app: bugdemo-pod
  serviceName: bugdemo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: bugdemo-pod
        extraLabel: fromPodTemplate
    spec:
      containers:
      - name: bugdemo-nginx
        image: nginx:stable
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-data
            mountPath: /var/log/dummy
  volumeClaimTemplates:
    - metadata:
        name: nginx-data
        labels:
          app: bugdemo-volumeclaim
          extraLabel: fromVolumeClaimTemplate
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: "1Gi"
```

1. Deploy this as app bug-original
`kapp deploy -f bugdemo.yaml -a bug-original  --apply-default-update-strategy fallback-on-replace`
2. Then relabel the app to overwrite ownerships
`kapp deploy -f bugdemo.yaml -a relabel-bug  --apply-default-update-strategy fallback-on-replace --dangerous-override-ownership-of-existing-resources`

The labels on the StatefulSet will change, including the VolumeClaimTemplate labels, but these changes will not propagate to the PVC itself. 

A workaround for now could be to create another annotation, owned-for-updates or such, which would cause Kapp to explicitly do this propagation. I guess if the StatefulSet worked properly, one would not need such a workaround.
