### ISSUE TITLE
Kapp dosen't restart deployment on SealedSecret update

### ISSUE THREAD

**Issue by mhubig** [k14s/kapp#181]
**What steps did you take:**
I just updated a [Sealed Secret](https://github.com/bitnami-labs/sealed-secrets). The Sealed Secret is converted to a secret by the SealedSecrets controller and that Secret is consumed by a deployment within my app.

**What happened:**
Kapp just wants to update the Sealed Secret, nothing more.

**What did you expect:**
Kapp should also restart the deployment consuming the converted secret!

**Anything else you would like to add:**
Maybe you can add a method to specify such dependencies via some annotation?

**Environment:**

- kapp version (use `kapp --version`): 0.35.0
- OS (e.g. from `/etc/os-release`): Mac OSX 
- Kubernetes version (use `kubectl version`): v1.18.12-gke.300

**Comment by cari-lynn** [comment]
Hey @mhubig, thanks for opening this issue. 
Editing this comment since kapp supports this workflow

~~`kapp` does restart deployments that use [versioned](https://carvel.dev/kapp/docs/latest/diff/#versioned-resources) Secrets, and it would be nice if SealedSecrets could be used the same way. However, it's not as straightforward for SealedSecrets because the Secret conversion is done in a Controller. `kapp` applies the SealedSecret to the cluster, and then the SealedSecrets Controller converts it into a Secret.~~ 

~~It is possible for `kapp` to integrate with the SealedSecrets Controller, wait for it to complete, then restart the deployment, but that integration would need to know how the Controller works and what to do if an error happens.~~ 

~~It's a question of whether or not we want to integrate `kapp` with Controllers, which seems like a change in the direction of how the tool works now.~~

~~Please let me know your thoughts on this~~

**Comment by cari-lynn** [comment]
@mhubig After thinking about this issue more, I think I overcomplicated it in my previous comment. 

You can use kapp’s [versioned resource](https://carvel.dev/kapp/docs/latest/diff/#versioned-resources) annotation on the SealedSecret which will restart the deployments when the SealedSecret is updated. Versioned resources work by representing an update to a resource as a new resource, by adding a version to the resource's name. Use a kapp [Config](https://carvel.dev/kapp/docs/latest/config/) with template rules to specify exactly where it should update the name of the SealedSecret with the new versioned name. For example:

```
apiVersion: kapp.k14s.io/v1alpha1
kind: Config

templateRules:
- resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: bitnami.com/v1alpha1, kind: SealedSecret}
  affectedResources:
    objectReferences:
    - path: [spec, template, spec, containers, {allIndexes: true}, env, {allIndexes: true}, valueFrom, secretKeyRef]
      resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: apps/v1, kind: Deployment}
```

Lastly, you will need to create the SealedSecret with a [namespace-wide scope](https://github.com/bitnami-labs/sealed-secrets#scopes) in order to allow `kapp` to append the Secret name with a version.

Please let us know how this works for you.
