### ISSUE TITLE
kapp should be a little more lenient for poorly formatted manifests when kapp.k14s.io/versioned is involved

### ISSUE THREAD

**Issue by voor** [k14s/kapp#183]
**What steps did you take:**
kapp will happily apply things will `null` volumes, `null` envFrom, and `null` initContainers that should be arrays.  Unfortunately, when a configmap or other resource with the `kapp.k14s.io/versioned` comes into play kapp will start complaining that those `null` values are not iterable.

**What happened:**
kapp fails saying that an array should be iterable, when it's nil:

```
kapp: Error: ObjectRefSetMod for path 'spec,template,spec,containers,(all),envFrom,(all),secretRef' on resource 'deployment/harbor-clair (apps/v1) namespace: registry':
        Unexpected non-array found: <nil>
```

**What did you expect:**
kapp should check if the array exists prior to iterating over it.

**Anything else you would like to add:**
The following overlay can be a temporarily remediation:

```
#@ deploy = overlay.subset({"kind": "Deployment"})
#@ sts = overlay.subset({"kind": "StatefulSet"})
#@overlay/match by=overlay.or_op(deploy, sts),expects="1+"
---
spec:
  template:
    spec:
      #@overlay/match by=overlay.subset(None),expects="0+"
      #@overlay/remove
      volumes:
      #@overlay/match by=overlay.subset(None),expects="0+"
      #@overlay/remove
      initContainers:
      containers:
      #@overlay/match by=overlay.subset({"envFrom": None }),when="1+"
      -
        #@overlay/remove
        envFrom:
```

**Environment:**

- kapp version (use `kapp --version`):
- OS (e.g. from `/etc/os-release`):
- Kubernetes version (use `kubectl version`)

**Comment by danielhelfand** [comment]
Thanks for opening this. Would you mind sharing a simple example to help reproduce this?

**Comment by voor** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i-break-kapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: i-break-kapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: i-break-kapp
    spec:
      containers:
      - image: nginx
        envFrom: null
      volumes: null
      initContainers: null
---
apiVersion: v1
kind: Secret
metadata:
  name: i-am-here-to-trigger-kapp
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  not: used
```

Result should be similar to:
```
kapp: Error: ObjectRefSetMod for path 'spec,template,spec,containers,(all),envFrom,(all),secretRef' on resource 'deployment/i-break-kapp (apps/v1) namespace: default':
  Unexpected non-array found: <nil>
```
