### ISSUE TITLE
Clarifying sources and type for rebase rules

### ISSUE THREAD

**Issue by braunsonm** [k14s/kapp#189]
Hello,

I'm having a hard time understanding the `sources` and `type` on rebase rules. I don't think they are clearly documented. 

1. For `type:` I cannot find any documentation of what this accepts or what it is
2. For `sources` is `new` the values that the cluster has set? `existing` the values that I already have in my local YAML?

Take the following example:

```
@@ update mutatingwebhookconfiguration/defaults.webhook.kpack.io (admissionregistration.k8s.io/v1beta1) cluster @@
  ...
  2,  2   metadata:
  3     -   annotations: {}
      3 +   annotations:
      4 +     kapp.k14s.io/original: 'stuff'
      5 +     kapp.k14s.io/original-diff-md5: e053721e8727e53200a8cd368a0681d9
  4,  6     creationTimestamp: "2020-11-16T15:31:49Z"
  5,  7     generation: 37346935
```

```
- paths:
  - [metadata, annotations]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - anyMatcher:
      matchers:
      - apiVersionKindMatcher:
          apiVersion: admissionregistration.k8s.io/v1beta1
          kind: MutatingWebhookConfiguration
          name: defaults.webhook.kpack.io
```

This rebase does not apply, I'm trying to figure out why this is and how maybe the documentation lead me astray. I'm not entirely sure why this annotation seems to get applied everytime and appear in my diff so I want to ignore it.

If I remove this rule all together I'm stuck with the original problem:

```
          +   4,  4   metadata:
          +   5     -   annotations: {}
          +   6,  5     creationTimestamp: "2020-11-16T15:31:57Z"
          +   7,  6     labels:
```

Kapp wants to delete this every time I deploy. This isn't just the case with annotations either, it happens on other types:

```
- paths:
  - [secrets, {index: 1}, name]
  type: copy
  sources: [existing, new] # tried both combinations here
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: ServiceAccount
      name: cc-kpack-registry-service-account
      namespace: cf-workloads-staging
```

Can never get rid of the following diff after multiple deploys:

```
@@ update serviceaccount/cc-kpack-registry-service-account (v1) namespace: cf-workloads-staging @@
          +   7,  6     labels:
          +   ...
          +  49, 48   - name: cc-kpack-registry-auth-secret-ver-2
          +  50     - - name: cc-kpack-registry-service-account-token-srmz6
          +  51, 49   
```

I want this secret to stay, it's applied by a controller and gets added back, but kapp does not want to ignore these deletions.
