### ISSUE TITLE
Missing annotation objects are not treated deterministically

### ISSUE THREAD

**Issue by braunsonm** [k14s/kapp#190]
**What steps did you take:**
1. Deploy a resource without an `annotations` block like so:

```yaml
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.kpack.io
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: kpack-webhook
      namespace: kpack
  failurePolicy: Fail
  sideEffects: None
  name: validation.webhook.kpack.io
```

2. Now deploy it again with a diff

```
          +   ...
          +   2,  2   metadata:
          +   3     -   annotations: {}
          +   4,  3     creationTimestamp: "2020-11-16T15:31:49Z"
          +   5,  4     generation: 388
```

**What happened:**
A diff is always created for this resource even though it has not changed.

**What did you expect:**
The kapp deployment should be idempotent. It seems like kapp removes the kapp specific annotations but leaves behind a empty annotations object which causes a deployment to always trigger again.

**Additional Information:**
Automation in our deployments and reproducable deploys are important to us as we deploy with kapp often. This bug creates a lot of noise in some of our deployments and we do not want to have to change our manifest to fit a format that kapp likes.

**Comment by pivotaljohn** [comment]
One observed case is when the only annotations on the resource in the cluster are those applied by `kapp` itself.

When considering a resource without its history, those annotations are removed leaving the `annotations:` key with an empty map value.

https://github.com/vmware-tanzu/carvel-kapp/blob/cb948046934a0ed1fae3bb3865a63ac863b6f7b3/pkg/kapp/diff/resource_with_history.go#L187-L192

In this specific situation, should the `annotations:` entry be removed entirely?

**Comment by joaopapereira** [comment]
Hey @braunsonm I was not able to reproduce this particular problem, these were the steps I did.

1. create the file `test.yml` with the following content:
   ```yaml
   ---
   apiVersion: admissionregistration.k8s.io/v1beta1
   kind: ValidatingWebhookConfiguration
   metadata:
     name: validation.webhook.kpack.io
   webhooks:
   - admissionReviewVersions:
     - v1beta1
     clientConfig:
       service:
         name: kpack-webhook
         namespace: kpack
     failurePolicy: Fail
     sideEffects: None
     name: validation.webhook.kpack.io
   ```
1. Executed
   ```
   ❯ kapp deploy -a missing-obj -f test.yml --diff-changes
   Target cluster 'https://127.0.0.1:51295' (nodes: kind-control-plane)
   
   @@ create validatingwebhookconfiguration/validation.webhook.kpack.io (admissionregistration.k8s.io/v1beta1) cluster @@
         0 + apiVersion: admissionregistration.k8s.io/v1beta1
         1 + kind: ValidatingWebhookConfiguration
         2 + metadata:
         3 +   labels:
         4 +     kapp.k14s.io/app: "1612903099649952000"
         5 +     kapp.k14s.io/association: v1.3c4cb9c91d8d8f6e41b6cf3b105f3d9f
         6 +   name: validation.webhook.kpack.io
         7 + webhooks:
         8 + - admissionReviewVersions:
         9 +   - v1beta1
        10 +   clientConfig:
        11 +     service:
        12 +       name: kpack-webhook
        13 +       namespace: kpack
        14 +   failurePolicy: Fail
        15 +   name: validation.webhook.kpack.io
        16 +   sideEffects: None
        17 +
   
   Changes
   
   Namespace  Name                         Kind                            Conds.  Age  Op      Op st.  Wait to    Rs  Ri
   (cluster)  validation.webhook.kpack.io  ValidatingWebhookConfiguration  -       -    create  -       reconcile  -   -
   
   Op:      1 create, 0 delete, 0 update, 0 noop
   Wait to: 1 reconcile, 0 delete, 0 noop
   
   Continue? [yN]: y
   
   3:38:26PM: ---- applying 1 changes [0/1 done] ----
   3:38:26PM: create validatingwebhookconfiguration/validation.webhook.kpack.io (admissionregistration.k8s.io/v1beta1) cluster
   3:38:26PM: ---- waiting on 1 changes [0/1 done] ----
   3:38:26PM: ok: reconcile validatingwebhookconfiguration/validation.webhook.kpack.io (admissionregistration.k8s.io/v1beta1) cluster
   3:38:26PM: ---- applying complete [1/1 done] ----
   3:38:26PM: ---- waiting complete [1/1 done] ----
   
   Succeeded
   ```
3. Without changing anything I did
   ```
   ❯ kapp deploy -a missing-obj -f test.yml --diff-changes
   Target cluster 'https://127.0.0.1:51295' (nodes: kind-control-plane)
   
   Changes
   
   Namespace  Name  Kind  Conds.  Age  Op  Op st.  Wait to  Rs  Ri
   
   Op:      0 create, 0 delete, 0 update, 0 noop
   Wait to: 0 reconcile, 0 delete, 0 noop
   
   Succeeded
   ```

In my case it doesn't show any diff. What do I need to do to replicate this problem?
I was using `kapp` version 0.35.0 on a MacOS. What version of `kapp` are you using and what OS?
