### ISSUE TITLE
Use waitRules to wait for custom resource

### ISSUE THREAD

**Issue by johny-mnemonic** [k14s/kapp#192]
I have tried to find more examples of using waitRules, but even mighty Google is silent, so I would like to ask for help here.
I am delivering CRD for Kubernetes Operator (more specifically MinIO Operaror) by Kapp, and would like to convince Kapp to wait for the object created by the Operator.

I am adding this Kapp config to the list of CRDs, but it doesn't seems to work:
```
---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
metadata:
  name: kapp-config

minimumRequiredVersion: 0.29.0

waitRules:
- supportsObservedGeneration: true
  conditionMatchers:
  - type: Ready
    status: "False"
    failure: true
  - type: Ready
    status: "True"
    success: true
  resourceMatchers:
  - kindNamespaceNameMatcher: {kind: Pod, namespace: minio, name: minio-zone-0-0}
```

Any hint what I might be doing wrong would help.
I hope that this is not some antipattern. With recent sprawl of operators, I guess it will be pretty common to still deliver the app by Kapp, but with the operator, it means delivering only it's definition/config for the operator, not the actual app itself.

Edit: It would be even better to wait for the minio service same way as Kapp normally do (i.e. for /v1/Service kind wait for spec.clusterIP). Which means I don't even need to define custom wait rules, just a custom resource to wait for.
