### ISSUE TITLE
Consider Expanding default rebase rules for webhooks (admission and validating)

### ISSUE THREAD

**Issue by voor** [k14s/kapp#197]
**Describe the problem/challenge you have**
Following is needed to help with defaulting in both webhooks:

```
# knative populates webhooks from the controller, so need to ignore these rules.
- paths:
  - [webhooks, {allIndexes: true}, rules]
  - [webhooks, {allIndexes: true}, reinvocationPolicy]
  - [webhooks, {allIndexes: true}, clientConfig, service, path]
  - [webhooks, {allIndexes: true}, clientConfig, service, port]
  - [webhooks, {allIndexes: true}, namespaceSelector]
  - [webhooks, {allIndexes: true}, matchPolicy]
  - [webhooks, {allIndexes: true}, objectSelector]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
  - apiVersionKindMatcher:
      apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
```

**Describe the solution you'd like**
Possibly consider if some of these should be in the default kapp config

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Comment by cppforlife** [comment]
```yaml
paths:
  - [webhooks, {allIndexes: true}, rules]
  - [webhooks, {allIndexes: true}, reinvocationPolicy]
  - [webhooks, {allIndexes: true}, clientConfig, service, path]
  - [webhooks, {allIndexes: true}, clientConfig, service, port]
  - [webhooks, {allIndexes: true}, namespaceSelector]
  - [webhooks, {allIndexes: true}, matchPolicy]
  - [webhooks, {allIndexes: true}, objectSelector]
sources: [new, existing]
```

these rules seem to be fairly wide reaching since they would fallback to using existing configuration when no new config is found. this can become problematic for general usage since if somebody decides to no longer set namespaceSelector anymore, kapp would copy over existing namespaceSelector.

overall i think this looks like config that's somewhat knative specific in how they deal with webhooks.
