### ISSUE TITLE
kapp deploy with "--logs-all" doesn't stop after deployment

### ISSUE THREAD

**Issue by StarpTech** [k14s/kapp#220]
**What happened:**
Sometimes when running `kapp deploy --allow-ns staging --allow-ns production -a ${profile} -f- -c -y --logs-all` in Github action the command will never stop and I see consecutive logs from the pods. When I remove `--logs-all` it works normally.

**What did you expect:**
Printing logs should stop after the successful deployment.

**Environment:**

- kapp version (use `kapp --version`): 0.36.0
- OS (e.g. from `/etc/os-release`): Ubuntu
- Kubernetes version (use `kubectl version`) v1.19.7

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
@StarpTech any correlation to anything going on? e.g. gets stuck when deployment has failed, or anything like that? how frequently does this happen?

**Comment by cppforlife** [comment]
actually im not seeing how this could be possible since tailing of logs happens in a go routine so it doesnt block exit of deploy command. what is the last line of output you are seeing? are you sure that kapp deploy is blocking and not something else? are you seeing https://github.com/vmware-tanzu/carvel-kapp/blob/develop/cmd/kapp/kapp.go#L48 printed?

**Comment by StarpTech** [comment]
> any correlation to anything going on? e.g. gets stuck when deployment has failed, or anything like that? how frequently does this happen?

No, the deployment was successful but the tailing process has never stopped.

> are you seeing https://github.com/vmware-tanzu/carvel-kapp/blob/develop/cmd/kapp/kapp.go#L48 printed?

Yes, after 7min and 300MB of logs in the Github action. According to the logs, the probes endpoints were called multiple times per second.

```yaml
 readinessProbe:
    httpGet:
      path: /health
      port: 5002
    initialDelaySeconds: 20
    periodSeconds: 30
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 5
  livenessProbe:
    httpGet:
      path: /health
      port: 5002
    initialDelaySeconds: 20
    periodSeconds: 30
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 5
```
