### ISSUE TITLE
remove conditions column from inspect/diff since it's misleadingly colored for resources like HPA which always have a false condition

### ISSUE THREAD

**Issue by StarpTech** [k14s/kapp#235]
**What steps did you take:**

```
Namespace  test  
Name       test-71295  
Kind       HorizontalPodAutoscaler  
Status     conditions:  
           - lastTransitionTime: "2021-06-24T11:56:39Z"  
             message: recommended size matches current size  
             reason: ReadyForNewScale  
             status: "True"  
             type: AbleToScale  
           - lastTransitionTime: "2021-06-24T12:41:27Z"  
             message: the HPA was able to successfully calculate a replica count from cpu resource  
               utilization (percentage of request)  
             reason: ValidMetricFound  
             status: "True"  
             type: ScalingActive  
           - lastTransitionTime: "2021-06-24T11:58:24Z"  
             message: the desired count is within the acceptable range  
             reason: DesiredWithinRange  
             status: "False"  
             type: ScalingLimited  
           currentMetrics:  
           - resource:  
               current:  
                 averageUtilization: 3  
                 averageValue: 16m  
               name: cpu  
             type: Resource  
           currentReplicas: 1  
           desiredReplicas: 1  
           lastScaleTime: "2021-06-24T12:45:06Z"
```

```
Namespace           Name                              Kind                     Owner    Conds.  Rs  Ri  Age  
test  				test-71295                        HorizontalPodAutoscaler  kapp     2/3 t   ok  -   52m  
```

**What happened:**

`ScalingLimited: false` is interpreted as an error.

**What did you expect:**
ScalingLimited indicates that autoscaling is not allowed because a maximum or minimum replica count was reached.

A True condition indicates that you need to raise or lower the minimum or maximum replica count in order to scale.

A False condition indicates that the requested scaling is allowed.

Source: https://docs.openshift.com/container-platform/3.9/dev_guide/pod_autoscaling.html

**Environment:**

- kapp version (use `kapp --version`): 0.37.0
- OS (e.g. from `/etc/os-release`): Ubuntu
- Kubernetes version (use `kubectl version`): 1.19.4

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
