### ISSUE TITLE
automatically show logs for pods that are not progressing during deploy

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp#3]
example:

knative-v0.4.0 requires particular kubernetes version, hence some pods will log and fail

pod/controller-f84547646-gqs69 logs:

```
...
{"level":"fatal","ts":"2019-03-19T00:25:40.784Z","logger":"controller","caller":"controller/main.go:118","msg":"Version check failed: kubernetes version \"v1.10.11-gke.1\" is not compatible, need at least \"v1.11.0\"","stacktrace":"main.main\n\t/go/src/github.com/knative/serving/cmd/controller/main.go:118\nruntime.main\n\t/root/sdk/go1.12rc1/src/runtime/proc.go:200"}
```

progress log:

```
5:26:10PM: waiting on update deployment/controller (apps/v1) namespace: knative-serving
5:26:11PM:  L waiting on replicaset/controller-f84547646 (extensions/v1beta1) namespace: knative-serving ... done
5:26:11PM:  L waiting on replicaset/controller-cf84485f7 (extensions/v1beta1) namespace: knative-serving ... done
5:26:11PM:  L waiting on replicaset/controller-5b569b8fb9 (extensions/v1beta1) namespace: knative-serving ... done
5:26:11PM:  L waiting on pod/controller-f84547646-gqs69 (v1) namespace: knative-serving ... in progress: Condition Ready is not True (False)
```

pod/controller-f84547646-gqs69 status:

```yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-03-19T00:19:53Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-03-19T00:22:54Z
    message: 'containers with unready status: [controller]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2019-03-19T00:19:53Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b87c0cf02ff2b04f9a3dac7c74c0ef04ae5fa8eddcec3c709209e5215dd20037
    image: sha256:ce2543ec455281f6904cbbf3304f840a619c0adaefc4bfa81964a1fadbfcaf13
    imageID: docker-pullable://gcr.io/knative-releases/github.com/knative/serving/cmd/controller@sha256:c9987a7b21400bd3afa01eeed54f390a7d1d24b25d87219803cdfb294a969379
    lastState:
      terminated:
        containerID: docker://b87c0cf02ff2b04f9a3dac7c74c0ef04ae5fa8eddcec3c709209e5215dd20037
        exitCode: 1
        finishedAt: 2019-03-19T00:25:40Z
        reason: Error
        startedAt: 2019-03-19T00:25:40Z
    name: controller
    ready: false
    restartCount: 6
    state:
      waiting:
        message: Back-off 5m0s restarting failed container=controller pod=controller-f84547646-gqs69_knative-serving(b7dc08dc-49dc-11e9-9fb1-42010a8001ed)
        reason: CrashLoopBackOff
  hostIP: 10.128.0.17
  phase: Running
  podIP: 10.20.3.180
  qosClass: Burstable
  startTime: 2019-03-19T00:19:53Z
```
