### ISSUE TITLE
--filter-labels isn't properly filtering CRD

### ISSUE THREAD

**Issue by jdef** [k14s/kapp#367]
**What steps did you take:**
[A clear and concise description steps and any files that can be used to reproduce the problem.]
```
:; kapp deploy -a someapp -y -f foo.yaml --filter-labels=a.b.c/bar=qaz
```

**What happened:**
[A small description of the result]
kapp complained about not finding custom resource types for several CRDs. the CRDs should have been filtered out (read: excluded from consideration) by the `--filter-labels` flag, but kapp was still processing them somehow.

**What did you expect:**
[A description of what was expected]
expected kapp to ignore all resources in foo.yaml that do not have labels matching the specified filter

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- kapp version (use `kapp --version`): 0.42.0
- OS (e.g. from `/etc/os-release`):
- Kubernetes version (use `kubectl version`)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by jdef** [comment]
xref #272

**Comment by renuy** [comment]
Hey @jdef , 
Could share your config please. 
Thanks

**Comment by renuy** [comment]
Also, please try kapp deploy -a someapp -y -f foo.yaml --filter-labels=a.b.c/bar!=qaz to exclude.
(the "not equal" to)

**Comment by jdef** [comment]
Sorry I cannot share my yaml or copy paste the exact error messages. These nodes are airgapped, and copy/paste isn't possible. Here's a "by hand" re-typed version of the error message, redacted appropriately.

```bash
Target cluster 'https://xxxxxxx:port/' (nodes: xxxxx)

kapp: Error: Expected to find kind 'constraints.gatekeeper.sh/v1beta1/CustomType', but did not:
- Kubernetes API server did not have matching apiVersion + kind
- no matching CRD was found in given configuration
```

Consider the yaml configuration:
```yaml
---
kind: CustomType
apiVersion: constraints.gatekeeper.sh/v1beta1
metadata:
  labels:
    a.b.c/bar=boo
  ...

---
kind: ConfigMap
metadata:
  labels:
    a.b.c/bar=qaz
```

My expectation is that `--filter-labels a.b.c/bar=qaz` would mask the CustomType resource so that `kapp deploy ...` would only consider the ConfigMap resource.

**Comment by cppforlife** [comment]
@jdef confirmed as a challenge with following setup

```
kind: Foo        # unknown kind to the cluster
apiVersion: v1
metadata:
  name: foo
  labels:
    kind-lbl: foo
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm
  labels:
    kind-lbl: cm
```

`kapp deploy -a test -f <(pbpaste) --filter-labels kind-lbl=cm` results in the same error as mentioned above due to `Foo` kind not being known to kapp (and to the cluster).

reason: filtering currently is done after preparation (internal step to fill in namespace, label resources, etc). one challenge i see with moving filtering to be done earlier is that namespace filter wont properly work. not yet sure how i feel about this.

alternative solution: can use carvel.dev/ytt to "shape" your configuration before passing it onto kapp. you can use ytt overlays to remove any resource with particular label (or without label, etc.).

additional note: we are working on a PR that actually makes it possible for gatekeeper constraints and gatekeeper installation itself to live in the same "kapp deploy" (https://github.com/vmware-tanzu/carvel-kapp/pull/319/files).

**Comment by jdef** [comment]
I'm actually trying to replace our existing preprocessing w/ the `--filter-labels` flag :)  So something like ytt isn't really a step forward at this point.

Happy to hear about #319 , we are interested in that too. In this case, our automation is trying to deploy something completely unrelated to gatekeeper - it just so happens that this is the "type not found" bump that we hit first.

**Comment by praveenrewar** [comment]
> I'm actually trying to replace our existing preprocessing w/ the --filter-labels flag 

@jdef I would like to understand more about what kind of preprocessing you are trying to do. 

In case you just want kapp to ignore the CustomResources and you are comfortable doing it without the labels, then you can use the [kapp.k14s.io/noop](https://carvel.dev/kapp/docs/latest/apply/#kappk14sionoop) annotation. 
However, you would have to provide the basic details of the CustomeResourceDefinition for the missing CustomTypes. 
So, for the yaml you had provided you would have to do something like
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customtype.constraints.gatekeeper.sh
  annotations:
    kapp.k14s.io/noop: ""
spec:
  group: constraints.gatekeeper.sh
  versions:
    - name: v1beta1
  names:
    kind: CustomType
---
kind: CustomType
apiVersion: constraints.gatekeeper.sh/v1beta1
metadata:
  name: foo
  annotations:
    kapp.k14s.io/noop: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bar
  namespace: kapp-test
```
And then `kapp deploy -a test -f <(pbpaste)` would only deploy the config map and ignore the other resources.

(This does seem a bit too much but just thought of sharing as a possible workaround)
