### ISSUE TITLE
How do I opt-in for 3-way merge?

### ISSUE THREAD

**Issue by redbaron** [k14s/kapp#385]
Hi, I read https://github.com/vmware-tanzu/carvel-kapp/issues/58 and appreciate reasoning you gave there. There is however a problem I can't resolve, hence this question.

First, to specify conflict resolution rule I need to know exactly where conflict might happen. Given that neither app author nor app deployer might be aware of manual changes done to the cluster resources , it is hard to for them to anticipate and provide conflict resolution configuration.

Second, assuming one would like to opt-in into 3 way merge, how to get it working in practice? Lets take a simple ConfigMap as an example, what rebaseRule config would look like for to get 3 way merge working?  More precisely:

- if key was added manually or (existing key modified manually and not changed between last applied config and new config), keep this key in the configmap applying any other changes in the new config
- if key was added manually or (exiting key modified  manually and changed between last applied config) generate conflict error, unless value provided manually is exactly the same as in new config.

Example of this behaviur would be:

Deploy following manifest:
```
data:
  key1: val1
```

Edit configmap manually via kubectl adding new key:
```
data:
  key1: val2
  key2: val2   # added manually via kubectl
```

Deploy new manifest:

```
data:
  key1: val1
  key3: val3
```

Expected result in the cluster:

```
data:
  key1: val1
  key2: val2
  key3: val3
```

I tried following config with no success:

```
rebaseRules:
- path: [data]  # also tried [data, {allIndexes: true}] which resulted in panic
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: ConfigMap}
```
