### ISSUE TITLE
additional default config

### ISSUE THREAD

**Issue by cppforlife** [k14s/kapp#49]
this issue is to track proposed additional deploy config that shuold be added to kapp. current default config can be seen via `kapp deploy-config`.

**Comment by cppforlife** [comment]
BogdanL reported unexpected diffing of PVs: https://kubernetes.slack.com/archives/CH8KCCKA5/p1573590861170100. Suggestion was to add PV `claimRef` and some other fields as rebase rules (https://gist.github.com/cppforlife/149872f132d6afdc6f0240d70f598a16)

**Comment by cppforlife** [comment]
- [x] suggestion to add Job as a target for templatRules for ConfigMap/Secret
- [x] fallback on existing spec.healthCheckNodePort for v1/Service

**Comment by cppforlife** [comment]
template rules for CronJob (https://gist.github.com/cppforlife/56d44562d6b44e529a3c5299bb2d8943)

**Comment by cppforlife** [comment]
aggregated rbac rules: https://github.com/k14s/kapp/issues/140#issuecomment-684104068

**Comment by caphrim007** [comment]
not sure if this is the appropriate location to put this, but HorizontalPodAutoscaler will modify the HPA annotations like so

```
  0,  0   apiVersion: autoscaling/v1
  1,  1   kind: HorizontalPodAutoscaler
  2,  2   metadata:
  3     -   annotations:
  4     -     autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True",...count"}]'
```

and kapp will always remove these and HPA will just add them back. I (personally) include a rebase rule to tell kapp to ignore this (because the HPA manages it). Here's the rule I use

```
      - path: [metadata, annotations, autoscaling.alpha.kubernetes.io/conditions]
        type: copy
        sources: [existing, new]
        resourceMatchers:
          - apiVersionKindMatcher: {apiVersion: autoscaling/v1, kind: HorizontalPodAutoscaler}
```
