### ISSUE TITLE
Add example for ownershipLabelRules

### ISSUE THREAD

**Issue by scothis** [k14s/kapp#582]
I couldn't find an example of how [`ownershipsLabelRules`](https://carvel.dev/kapp/docs/v0.51.0/config/#ownershiplabelrules) are expected to work.

I was trying to show logs from a Pod managed by a Knative Service, despite adding the log annotations to the resulting Pod and using `--logs` with my deploy command, nothing was showing up...

By reading the source, this seems to solve my issue, but I don't know if I might be "holding it wrong."
```
ownershipLabelRules:
- path: [spec, template, metadata, labels]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: serving.knative.dev/v1, kind: Service}
```

Besides adding this to the website docs, it might be worth adding to the knative examples as well.
