### ISSUE TITLE
diffAgainstLastAppliedFieldExclusionRules with Secret

### ISSUE THREAD

**Issue by schmurfy** [k14s/kapp#634]
I am deploying a `Secret` which is updated at runtime, I tried to add a kapp config to not override the data set but I cannot make it works:

```
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
diffAgainstLastAppliedFieldExclusionRules:
  - path: ["webhooks", {allIndexes: true}, "clientConfig", "caBundle"]
    resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: "admissionregistration.k8s.io/v1", kind: "MutatingWebhookConfiguration"}
  - path: ["data"]
    resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: "v1", kind: "Secret"}
```

The first part for `MutatingWebhookConfiguration` works well so I know the config is really used but I cannot make the `Secret` rule works and I am at a loss as to why it does not work.

Here is an example of the targeted `Secret`:
```
---
# Source: vault/templates/injector-certs-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: vault-injector-certs
  namespace: default
  labels:
    toto: titi
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault-agent
    app.kubernetes.io/managed-by: Helm
```

**Comment by praveenrewar** [comment]
Hi @schmurfy! If I understood correctly, you don't want kapp to overwrite/remove some fields of a Secret present on the cluster. If so, you can use [rebase rules](https://carvel.dev/kapp/docs/v0.53.0/config/#rebaserules) to copy the fields from the cluster that you don't want to overwrite.

**Comment by schmurfy** [comment]
My initial idea is for kapp to see that the Secret has not changed between what I wanted:
```
apiVersion: v1
kind: Secret
metadata:
  name: vault-injector-certs
  namespace: default
  labels:
    toto: titi
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault-agent
    app.kubernetes.io/managed-by: Helm
```

and what is deployed:
```
apiVersion: v1
kind: Secret
metadata:
  name: vault-injector-certs
  namespace: default
  labels:
    toto: titi
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: vault-agent
    app.kubernetes.io/managed-by: Helm
data:
  key1: sfsdfgd
  key2: fhhjhgjj
```

I suppose rebase rules could work too but what I really wanted is for kapp to do nothing because with the `data` field ignored both manifests are the same.
