### ISSUE TITLE
rebaseRules does not add new keys/values to an existing secret

### ISSUE THREAD

**Issue by steve-todorov** [k14s/kapp#662]
**What steps did you take:**

`rebaseRules` configured with `sources: [existing, new]` does not add new keys/values to an existing secret.

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kapp-config
  labels:
    kapp.k14s.io/config: ""
data:
  config.yml: |
    apiVersion: kapp.k14s.io/v1alpha1
    kind: Config
    rebaseRules:
      - path: [data]
        type: copy
        # Do not overwrite already configured credentials, but copy new placeholder fields when they are added and do not exist in upstream.
        sources: [existing, new]
        resourceMatchers:
        - apiVersionKindMatcher: {apiVersion: v1, kind: Secret}

---
apiVersion: v1
kind: Secret
metadata:
  name: backup-secrets
  annotations:
    kapp.k14s.io/disable-original: ""
type: Opaque
data:
  AWS_ACCESS_KEY_ID: MTIzNAo= (already exists prior running kapp deploy)
  AWS_SECRET_ACCESS_KEY: MTIzNAo= (already exists prior running kapp deploy)
  AWS_DEFAULT_REGION: MTIzNAo= (already exists prior running kapp deploy)
  AWS_S3_BUCKET: MTIzNAo= (already exists prior running kapp deploy)
+ TEST: MTIzNAo= (exists only locally and should be added in kubernetes, because it's completely missing from upstream)
```

**What happened:**

When you run kapp deploy it does not detect it needs to add the `TEST` key/value secret and completely ignores it.

```
KAPP_FQ_CONFIGMAP_NAMES=true kapp deploy -n default -a my-app -f ./ --diff-changes

Changes

Namespace  Name  Kind  Age  Op  Op st.  Wait to  Rs  Ri  

Op:      0 create, 0 delete, 0 update, 0 noop, 0 exists
Wait to: 0 reconcile, 0 delete, 0 noop

Succeeded
```

**What did you expect:**

Following the documentation, I expected that the `TEST` key would have been added to the `backup-secrets` as it is a new value that does not exist.

```

@@ update secret/backup-secrets (v1) namespace: default @@
  ...
  1,  1   data:
  2,  2     AWS_ACCESS_KEY_ID: <-- value not shown (#1)
  3,  3     AWS_DEFAULT_REGION: <-- value not shown (#2)
  4,  4     AWS_S3_BUCKET: <-- value not shown (#3)
      5 +   TEST: <-- value not shown (#4)


Changes

Namespace  Name                     Kind       Age  Op      Op st.  Wait to    Rs  Ri  
default    backup-secrets           Secret     9m   update  -       reconcile  ok  -  

```

**Environment:**

- kapp version (use `kapp --version`): `kapp version 0.54.0`
- OS (e.g. from `/etc/os-release`): `Ubuntu 22.10`
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.24.2
```

**Additional details:**

Possibly indirectly related to: 
#191, #124 and maybe a few other tickets.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
Hey @steve-todorov with 
```
- path: [data]
  type: copy
  sources: [existing, new]
```
you are basically saying, copy the `data` field from existing resource if it exists and if not, then copy it from the new resource and I think what you need is the same rule applied to individual keys in `data` and not `data` itself.

**Comment by steve-todorov** [comment]
@praveenrewar thanks for the fast reply!

Ahh I see what you mean. Is there a way to do this in a more a "global" manner instead of specifying it field, by field?

Also, would you mind showing me an example of how you'd apply this rule for the individual keys? I can't seem to find the right combination. Is it supposed to be like this:

```
- path: [ data, data.TEST ]
```

**Comment by steve-todorov** [comment]
Okay, so if I use this yaml:

```yaml
    apiVersion: kapp.k14s.io/v1alpha1
    kind: Config
    # Do not overwrite existing credentials, but do copy new placeholder fields when that's necessary.
    rebaseRules:
      - paths: 
        - [ data, AWS_ACCESS_KEY_ID ]
        - [ data, AWS_SECRET_ACCESS_KEY ]
        - [ data, AWS_DEFAULT_REGION ]
        - [ data, AWS_S3_BUCKET ]
        - [ data, TEST ]
        type: copy
        sources: [existing, new]
        resourceMatchers:
        - apiVersionKindMatcher: {apiVersion: v1, kind: Secret}
```

It works as expected. The only downside is I need to put all keys manually which might be error prone as you need to keep in mind to sync the values if they change. It might be useful if there was a wildcard option -- i.e.

```yaml 
    rebaseRules:
      - paths: 
        - [ data, "*" ]
```

which would match app keys.
