### ISSUE TITLE
Include default template rules for Knative services

### ISSUE THREAD

**Issue by praveenrewar** [k14s/kapp#668]
**Describe the problem/challenge you have**
Versioned resources (with a generated name) are not taken into account for Knative services

**Describe the solution you'd like**
It would be great if kapp's default deploy config would be aware of knatives's references to Secrets and ConfigMaps
[Slack thread](https://kubernetes.slack.com/archives/CH8KCCKA5/p1672991015832859)

We can add template rules like one below for knative services to make kapp aware of CMs and Secrets.

```yaml
# Manage versioned configmap into serving.knative.dev/v1
templateRules:
- resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: ConfigMap}
  affectedResources:
    objectReferences:    
    - path: [spec, template, spec, volumes, {allIndexes: true}, configMap]    
      resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: serving.knative.dev/v1, kind: Service}
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
