### ISSUE TITLE
discussion: unix piping and error resource

### ISSUE THREAD

**Issue by brandonkal** [k14s/kapp#69]
Naturally these tools are great for piping things around. Perhaps it may be a good idea to define a generic Error object. Then tools upstream in the pipeline can emit these errors when they cannot proceed and they can be handled gracefully.

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: generatingToolName/v1
kind: Error
metadata:
  name: Warning
  message: Missing required parameter to generate Kubernetes Manifest
```

Essentially if kapp comes across an Error object, It will not allow deployment and will gracefully show the error received (rather than some generic unable to parse YAML). The kind would always be "Error" and any tool can define its own apiVersion.
