### ISSUE TITLE
Support storing deployed application state as a custom resource

### ISSUE THREAD

**Issue by ojhughes** [k14s/kapp#70]
**Issue you are facing** 
It is easy to forget which namespace `kapp` used to stored deployed app metadata

**Proposed solution**
Provide the option to store app state as Kubernetes resources, for example
```
apiVersion: kapp.k14s.io
kind: App
spec:
  lastChange: 
    startedAt:
  ...
```
