### ISSUE TITLE
Piping kbld into kapp fails

### ISSUE THREAD

**Issue by garethr** [k14s/kapp#74]
I get the following errors if I pipe `kbld` output into `kapp`:

```
kapp: Error: Validation errors:
- Expected 'apiVersion' on resource 'object/ () cluster' to be non-empty (stdin doc 1)
- Expected 'metadata.name' on resource 'object/ () cluster' to be non-empty (stdin doc 1)
```

I have the following image defined:

```yaml
---
kind: Object
spec:
- image: garethr/snykit
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: garethr/snykit
  path: .
---
```

Which results in the following being part of the resulting output.

```yaml
---
kind: Object
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Path: /Users/garethr/Documents/snykit
          Type: local
        - Dirty: true
          RemoteURL: git@github.com:garethr/snykit.git
          SHA: e099bb78c708ff046a899914c79b85fb2133e701
          Type: git
        URL: kbld:garethr-snykit-sha256-323b68bfefce19a2d370bc3472e21a0780d51e39dac50871f42105a1a45dccdb
spec:
- image: kbld:garethr-snykit-sha256-323b68bfefce19a2d370bc3472e21a0780d51e39dac50871f42105a1a45dccdb
---
```

This then fails the `kapp` validation step as noted.  Is this user error or a bug?
